step 1 : getting data  ( done)

step 2 : import libraries

In [33]:
import numpy as np
import pandas as pd

In [34]:

# Create and populate NumPy array.
my_data = np.array([
    ['France', 44.0, 72000.0, 'NO'],
    ['Spain', 27.0, 48000.0, 'YES'],
    ['Germany', 30.0, 54000.0, 'NO'],
    ['Spain', 38.0, 61000.0, 'NO'],
    ['Germany', 40.0, np.NaN, 'YES'],
    ['France', 35.0, 58000.0, 'YES'],
    ['Spain', np.NaN, 52000.0, 'NO'],
    ['France', 48.0, 79000.0, 'YES'],
    ['Germany', 50.0, 83000.0, 'NO'],
    ['France', 37.0, 67000.0, 'YES']
])

# Create a Python list that holds the names of the columns.
my_column_names = ['Country', 'Age', 'Salary', 'Purchased']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)


   Country   Age   Salary Purchased
0   France  44.0  72000.0        NO
1    Spain  27.0  48000.0       YES
2  Germany  30.0  54000.0        NO
3    Spain  38.0  61000.0        NO
4  Germany  40.0      nan       YES
5   France  35.0  58000.0       YES
6    Spain   nan  52000.0        NO
7   France  48.0  79000.0       YES
8  Germany  50.0  83000.0        NO
9   France  37.0  67000.0       YES


In [ ]:
# for reading the file
#this is used when we take data from outside
# but if are storing our data in variable we don't need to read it again
dataset= pd.read_csv("my_data.csv")
dataset

identify dependent and independent variable

lets take an example of a simple linear equation  x+y=z ( here x,y are in independent . z is dependent)

In [35]:
x = my_dataframe[['Country', 'Age', 'Salary']]
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      nan
5   France  35.0  58000.0
6    Spain   nan  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

for creating array of this add (.values)

In [36]:
x = my_dataframe[['Country', 'Age', 'Salary']].values
x  

array([['France', '44.0', '72000.0'],
       ['Spain', '27.0', '48000.0'],
       ['Germany', '30.0', '54000.0'],
       ['Spain', '38.0', '61000.0'],
       ['Germany', '40.0', 'nan'],
       ['France', '35.0', '58000.0'],
       ['Spain', 'nan', '52000.0'],
       ['France', '48.0', '79000.0'],
       ['Germany', '50.0', '83000.0'],
       ['France', '37.0', '67000.0']], dtype=object)

In [37]:
y= my_dataframe[['Purchased']]
y

Purchased
0        NO
1       YES
2        NO
3        NO
4       YES
5       YES
6        NO
7       YES
8        NO
9       YES

In [38]:
y= my_dataframe[['Purchased']].values
y

array([['NO'],
       ['YES'],
       ['NO'],
       ['NO'],
       ['YES'],
       ['YES'],
       ['NO'],
       ['YES'],
       ['NO'],
       ['YES']], dtype=object)

step 3 : finding missing values

if we have missing data 
we will fill that by using mean, median , mode

In [39]:
# SimpleImputer is a class belongs to sklearn
from sklearn.impute import SimpleImputer


In [40]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [50]:
# fit is a method
# imputer will take every missing values in rows or column
#take all row and 1 to 2 column
imputer = imputer.fit(x[:, 1:3])

In [51]:
# transform will replace all the missing values by mean
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [52]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

step 4: encoding categorical data

change the country and purchase data into numeric data (we change it bcz some algorithm does not work in categorial data )

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
LabelEncoder_x= LabelEncoder()

In [56]:
x[:,0]=LabelEncoder_x.fit_transform(x[:,0])

In [57]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

here we need to do dummy encoding bcz it can understad corelation between them bt it is not 

In [58]:
from sklearn.preprocessing import OneHotEncoder

In [59]:
OneHotEncoder=OneHotEncoder()

In [61]:
x=OneHotEncoder.fit_transform(my_dataframe.Country.values.reshape(-1,1)).toarray()

In [62]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [63]:
LabelEncoder_y=LabelEncoder()

In [64]:
y=LabelEncoder_y.fit_transform(y)

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [65]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

step 5: splitting dataset into training & test set

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
# ih this we have pass 4 arguments
# 20% of dataset is used to test the model
# x ,y are arrays
#bcz of random state every time give same value
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=2,random_state=0)

In [68]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [69]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [70]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [71]:
y_test

array([0, 0])

step 6: feature scaling

In [72]:
from sklearn.preprocessing import StandardScaler

In [73]:
sc_x=StandardScaler()

In [74]:
x_train=sc_x.fit_transform(x_train)

In [79]:
x_test=sc_x.fit_transform(x_test)

In [80]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [81]:
x_test

array([[0., 0., 0.],
       [0., 0., 0.]])